version: 1
services:
  - type: web
    name: SocketBox Demo
    runtime: image
    plan: free
    image:
      url: ortussolutions/boxlang:miniserver 
    autoDeploy: true  # Set to true for auto-deploy on push